# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: [
#       'build',
#       '-t', 'gcr.io/$PROJECT_ID/santa-video-generator',
#       '--build-arg', 'PROJECT_ID=$PROJECT_ID',
#       '.'
#     ]

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/santa-video-generator']

#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: [
#       'run',
#       'deploy',
#       'santa-video-generator',
#       '--image', 'gcr.io/$PROJECT_ID/santa-video-generator',
#       '--platform', 'managed',
#       # '--allow-unauthenticated',
#       '--port', '8080'
#     ]

# images:
#   - 'gcr.io/$PROJECT_ID/santa-video-generator'

steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=pkg.dev/$PROJECT_ID/santa-video-generator/app
      - --dockerfile=Dockerfile
      - --cache=true

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flutter-web'
      - '--image=pkg.dev/$PROJECT_ID/santa-video-generator/app'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
timeout: '300s'