steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/santa-video-generator/app:$COMMIT_SHA
      - --dockerfile=Dockerfile
      - --cache=true

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'santa-video-generator'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/santa-video-generator/app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'

timeout: '300s'